--- 
language: ruby
notifications: 
  email: 
    on_failure: always
    on_success: never
script: 
- git clone -q git://github.com/cloudsmith/ghpublisher.git .forge-releng
- .forge-releng/publish
env: 
  global: 
  - PUBLISHER_LOGIN=rcoleman
  - secure: |-
      Celrb09tc43ZzqX694IqxbZCZpcubsbBodMPSIRyZ4VnyIphYbrLf+jaQG3O
      7rYqDAziBtiOLPz53LcLRSIvCN3Iom9r407faTx/AuXJslpI4f0cXsTdQBkG
      QZaf2+dqvmwt3/2m5qVpOvmBuEcs3MRXp8fo5RZVMC5KjezOwD4=
